Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.box_check_update = false

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.12.10"
    master.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install php-geshi -y
    cd /var/www/html
    sudo wget https://download.dokuwiki.org/out/dokuwiki-8a269cc015a64b40e4c918699f1e1142.tgz
    sudo tar -xvf dokuwiki-8a269cc015a64b40e4c918699f1e1142.tgz
    sudo rm -Rf dokuwiki-8a269cc015a64b40e4c918699f1e1142.tgz
    sudo rm index.html
    cd dokuwiki/
    sudo mv * ../
    sudo chown -R vagrant:www-data /var/www/html/
    SHELL
  end

  config.vm.define "backup" do |backup|
    backup.vm.hostname = "backup"
    backup.vm.network "private_network", ip: "192.168.12.11"
    backup.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install php-geshi -y
    cd /var/www/html
    sudo wget https://download.dokuwiki.org/out/dokuwiki-8a269cc015a64b40e4c918699f1e1142.tgz
    sudo tar -xvf dokuwiki-8a269cc015a64b40e4c918699f1e1142.tgz
    sudo rm -Rf dokuwiki-8a269cc015a64b40e4c918699f1e1142.tgz
    sudo rm index.html
    cd dokuwiki/
    sudo mv * ../
    sudo chown -R vagrant:www-data /var/www/html/
    SHELL
  end
end